// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2Vqv3a9DeM6eVUu-iBvjd1Kze_J4cKCw',
    appId: '1:114850631367:web:3824361cac22b50bd538e2',
    messagingSenderId: '114850631367',
    projectId: 'e-commerce-dev-lucky',
    authDomain: 'e-commerce-dev-lucky.firebaseapp.com',
    storageBucket: 'e-commerce-dev-lucky.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh8BWyIpqTx8u89j-Kn2QaqWhf23eDsqY',
    appId: '1:114850631367:android:4033d82996b4ef8bd538e2',
    messagingSenderId: '114850631367',
    projectId: 'e-commerce-dev-lucky',
    storageBucket: 'e-commerce-dev-lucky.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqmfs7EJQ3HNRjR7YMLIf9NWWWfpMaDGg',
    appId: '1:114850631367:ios:cd978a6ffbcf19f0d538e2',
    messagingSenderId: '114850631367',
    projectId: 'e-commerce-dev-lucky',
    storageBucket: 'e-commerce-dev-lucky.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqmfs7EJQ3HNRjR7YMLIf9NWWWfpMaDGg',
    appId: '1:114850631367:ios:cd978a6ffbcf19f0d538e2',
    messagingSenderId: '114850631367',
    projectId: 'e-commerce-dev-lucky',
    storageBucket: 'e-commerce-dev-lucky.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2Vqv3a9DeM6eVUu-iBvjd1Kze_J4cKCw',
    appId: '1:114850631367:web:dd3771f078200f16d538e2',
    messagingSenderId: '114850631367',
    projectId: 'e-commerce-dev-lucky',
    authDomain: 'e-commerce-dev-lucky.firebaseapp.com',
    storageBucket: 'e-commerce-dev-lucky.firebasestorage.app',
  );
}